#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Travel")]
public partial class TravelDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAccount(Account instance);
  partial void UpdateAccount(Account instance);
  partial void DeleteAccount(Account instance);
  partial void InsertAmThuc_Comment_Rating(AmThuc_Comment_Rating instance);
  partial void UpdateAmThuc_Comment_Rating(AmThuc_Comment_Rating instance);
  partial void DeleteAmThuc_Comment_Rating(AmThuc_Comment_Rating instance);
  partial void InsertEvent(Event instance);
  partial void UpdateEvent(Event instance);
  partial void DeleteEvent(Event instance);
  partial void InsertTravel_Comment_Rating(Travel_Comment_Rating instance);
  partial void UpdateTravel_Comment_Rating(Travel_Comment_Rating instance);
  partial void DeleteTravel_Comment_Rating(Travel_Comment_Rating instance);
  partial void InsertEvent_Comment_Rating(Event_Comment_Rating instance);
  partial void UpdateEvent_Comment_Rating(Event_Comment_Rating instance);
  partial void DeleteEvent_Comment_Rating(Event_Comment_Rating instance);
  partial void InsertHotel_Comment_Rating(Hotel_Comment_Rating instance);
  partial void UpdateHotel_Comment_Rating(Hotel_Comment_Rating instance);
  partial void DeleteHotel_Comment_Rating(Hotel_Comment_Rating instance);
  partial void InsertRest_Comment_Rating(Rest_Comment_Rating instance);
  partial void UpdateRest_Comment_Rating(Rest_Comment_Rating instance);
  partial void DeleteRest_Comment_Rating(Rest_Comment_Rating instance);
  partial void InsertThongTinAmThuc(ThongTinAmThuc instance);
  partial void UpdateThongTinAmThuc(ThongTinAmThuc instance);
  partial void DeleteThongTinAmThuc(ThongTinAmThuc instance);
  partial void InsertThongTinNhaHang(ThongTinNhaHang instance);
  partial void UpdateThongTinNhaHang(ThongTinNhaHang instance);
  partial void DeleteThongTinNhaHang(ThongTinNhaHang instance);
  partial void InsertThongTinDuLich(ThongTinDuLich instance);
  partial void UpdateThongTinDuLich(ThongTinDuLich instance);
  partial void DeleteThongTinDuLich(ThongTinDuLich instance);
  partial void InsertThongTinKhachSan(ThongTinKhachSan instance);
  partial void UpdateThongTinKhachSan(ThongTinKhachSan instance);
  partial void DeleteThongTinKhachSan(ThongTinKhachSan instance);
  #endregion
	
	public TravelDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TravelConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TravelDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TravelDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TravelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TravelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Account> Accounts
	{
		get
		{
			return this.GetTable<Account>();
		}
	}
	
	public System.Data.Linq.Table<AmThuc_Comment_Rating> AmThuc_Comment_Ratings
	{
		get
		{
			return this.GetTable<AmThuc_Comment_Rating>();
		}
	}
	
	public System.Data.Linq.Table<Event> Events
	{
		get
		{
			return this.GetTable<Event>();
		}
	}
	
	public System.Data.Linq.Table<Travel_Comment_Rating> Travel_Comment_Ratings
	{
		get
		{
			return this.GetTable<Travel_Comment_Rating>();
		}
	}
	
	public System.Data.Linq.Table<Event_Comment_Rating> Event_Comment_Ratings
	{
		get
		{
			return this.GetTable<Event_Comment_Rating>();
		}
	}
	
	public System.Data.Linq.Table<Hotel_Comment_Rating> Hotel_Comment_Ratings
	{
		get
		{
			return this.GetTable<Hotel_Comment_Rating>();
		}
	}
	
	public System.Data.Linq.Table<Rest_Comment_Rating> Rest_Comment_Ratings
	{
		get
		{
			return this.GetTable<Rest_Comment_Rating>();
		}
	}
	
	public System.Data.Linq.Table<ThongTinAmThuc> ThongTinAmThucs
	{
		get
		{
			return this.GetTable<ThongTinAmThuc>();
		}
	}
	
	public System.Data.Linq.Table<ThongTinNhaHang> ThongTinNhaHangs
	{
		get
		{
			return this.GetTable<ThongTinNhaHang>();
		}
	}
	
	public System.Data.Linq.Table<ThongTinDuLich> ThongTinDuLiches
	{
		get
		{
			return this.GetTable<ThongTinDuLich>();
		}
	}
	
	public System.Data.Linq.Table<ThongTinKhachSan> ThongTinKhachSans
	{
		get
		{
			return this.GetTable<ThongTinKhachSan>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _User_ID;
	
	private string _UserName;
	
	private string _Pass;
	
	private string _Name;
	
	private string _Email;
	
	private string _Phone;
	
	private string _Address;
	
	private System.Nullable<bool> _Type;
	
	private System.Nullable<bool> _Active;
	
	private EntitySet<AmThuc_Comment_Rating> _AmThuc_Comment_Ratings;
	
	private EntitySet<Travel_Comment_Rating> _Travel_Comment_Ratings;
	
	private EntitySet<Event_Comment_Rating> _Event_Comment_Ratings;
	
	private EntitySet<Hotel_Comment_Rating> _Hotel_Comment_Ratings;
	
	private EntitySet<Rest_Comment_Rating> _Rest_Comment_Ratings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IDChanging(System.Guid value);
    partial void OnUser_IDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnTypeChanging(System.Nullable<bool> value);
    partial void OnTypeChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
	
	public Account()
	{
		this._AmThuc_Comment_Ratings = new EntitySet<AmThuc_Comment_Rating>(new Action<AmThuc_Comment_Rating>(this.attach_AmThuc_Comment_Ratings), new Action<AmThuc_Comment_Rating>(this.detach_AmThuc_Comment_Ratings));
		this._Travel_Comment_Ratings = new EntitySet<Travel_Comment_Rating>(new Action<Travel_Comment_Rating>(this.attach_Travel_Comment_Ratings), new Action<Travel_Comment_Rating>(this.detach_Travel_Comment_Ratings));
		this._Event_Comment_Ratings = new EntitySet<Event_Comment_Rating>(new Action<Event_Comment_Rating>(this.attach_Event_Comment_Ratings), new Action<Event_Comment_Rating>(this.detach_Event_Comment_Ratings));
		this._Hotel_Comment_Ratings = new EntitySet<Hotel_Comment_Rating>(new Action<Hotel_Comment_Rating>(this.attach_Hotel_Comment_Ratings), new Action<Hotel_Comment_Rating>(this.detach_Hotel_Comment_Ratings));
		this._Rest_Comment_Ratings = new EntitySet<Rest_Comment_Rating>(new Action<Rest_Comment_Rating>(this.attach_Rest_Comment_Ratings), new Action<Rest_Comment_Rating>(this.detach_Rest_Comment_Ratings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this.OnUser_IDChanging(value);
				this.SendPropertyChanging();
				this._User_ID = value;
				this.SendPropertyChanged("User_ID");
				this.OnUser_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(20)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(255)")]
	public string Pass
	{
		get
		{
			return this._Pass;
		}
		set
		{
			if ((this._Pass != value))
			{
				this.OnPassChanging(value);
				this.SendPropertyChanging();
				this._Pass = value;
				this.SendPropertyChanged("Pass");
				this.OnPassChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Bit")]
	public System.Nullable<bool> Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_AmThuc_Comment_Rating", Storage="_AmThuc_Comment_Ratings", ThisKey="User_ID", OtherKey="User_ID")]
	public EntitySet<AmThuc_Comment_Rating> AmThuc_Comment_Ratings
	{
		get
		{
			return this._AmThuc_Comment_Ratings;
		}
		set
		{
			this._AmThuc_Comment_Ratings.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Travel_Comment_Rating", Storage="_Travel_Comment_Ratings", ThisKey="User_ID", OtherKey="User_ID")]
	public EntitySet<Travel_Comment_Rating> Travel_Comment_Ratings
	{
		get
		{
			return this._Travel_Comment_Ratings;
		}
		set
		{
			this._Travel_Comment_Ratings.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Event_Comment_Rating", Storage="_Event_Comment_Ratings", ThisKey="User_ID", OtherKey="User_ID")]
	public EntitySet<Event_Comment_Rating> Event_Comment_Ratings
	{
		get
		{
			return this._Event_Comment_Ratings;
		}
		set
		{
			this._Event_Comment_Ratings.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Hotel_Comment_Rating", Storage="_Hotel_Comment_Ratings", ThisKey="User_ID", OtherKey="User_ID")]
	public EntitySet<Hotel_Comment_Rating> Hotel_Comment_Ratings
	{
		get
		{
			return this._Hotel_Comment_Ratings;
		}
		set
		{
			this._Hotel_Comment_Ratings.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Rest_Comment_Rating", Storage="_Rest_Comment_Ratings", ThisKey="User_ID", OtherKey="User_ID")]
	public EntitySet<Rest_Comment_Rating> Rest_Comment_Ratings
	{
		get
		{
			return this._Rest_Comment_Ratings;
		}
		set
		{
			this._Rest_Comment_Ratings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_AmThuc_Comment_Ratings(AmThuc_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = this;
	}
	
	private void detach_AmThuc_Comment_Ratings(AmThuc_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = null;
	}
	
	private void attach_Travel_Comment_Ratings(Travel_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = this;
	}
	
	private void detach_Travel_Comment_Ratings(Travel_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = null;
	}
	
	private void attach_Event_Comment_Ratings(Event_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = this;
	}
	
	private void detach_Event_Comment_Ratings(Event_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = null;
	}
	
	private void attach_Hotel_Comment_Ratings(Hotel_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = this;
	}
	
	private void detach_Hotel_Comment_Ratings(Hotel_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = null;
	}
	
	private void attach_Rest_Comment_Ratings(Rest_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = this;
	}
	
	private void detach_Rest_Comment_Ratings(Rest_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Account = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AmThuc_Comment_Rating")]
public partial class AmThuc_Comment_Rating : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Comment_ID;
	
	private System.Nullable<System.Guid> _User_ID;
	
	private System.Nullable<int> _AmThuc_ID;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private EntityRef<Account> _Account;
	
	private EntityRef<ThongTinAmThuc> _ThongTinAmThuc;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComment_IDChanging(int value);
    partial void OnComment_IDChanged();
    partial void OnUser_IDChanging(System.Nullable<System.Guid> value);
    partial void OnUser_IDChanged();
    partial void OnAmThuc_IDChanging(System.Nullable<int> value);
    partial void OnAmThuc_IDChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    #endregion
	
	public AmThuc_Comment_Rating()
	{
		this._Account = default(EntityRef<Account>);
		this._ThongTinAmThuc = default(EntityRef<ThongTinAmThuc>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Comment_ID
	{
		get
		{
			return this._Comment_ID;
		}
		set
		{
			if ((this._Comment_ID != value))
			{
				this.OnComment_IDChanging(value);
				this.SendPropertyChanging();
				this._Comment_ID = value;
				this.SendPropertyChanged("Comment_ID");
				this.OnComment_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				if (this._Account.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUser_IDChanging(value);
				this.SendPropertyChanging();
				this._User_ID = value;
				this.SendPropertyChanged("User_ID");
				this.OnUser_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmThuc_ID", DbType="Int")]
	public System.Nullable<int> AmThuc_ID
	{
		get
		{
			return this._AmThuc_ID;
		}
		set
		{
			if ((this._AmThuc_ID != value))
			{
				if (this._ThongTinAmThuc.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnAmThuc_IDChanging(value);
				this.SendPropertyChanging();
				this._AmThuc_ID = value;
				this.SendPropertyChanged("AmThuc_ID");
				this.OnAmThuc_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(250)")]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_AmThuc_Comment_Rating", Storage="_Account", ThisKey="User_ID", OtherKey="User_ID", IsForeignKey=true)]
	public Account Account
	{
		get
		{
			return this._Account.Entity;
		}
		set
		{
			Account previousValue = this._Account.Entity;
			if (((previousValue != value) 
						|| (this._Account.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Account.Entity = null;
					previousValue.AmThuc_Comment_Ratings.Remove(this);
				}
				this._Account.Entity = value;
				if ((value != null))
				{
					value.AmThuc_Comment_Ratings.Add(this);
					this._User_ID = value.User_ID;
				}
				else
				{
					this._User_ID = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("Account");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinAmThuc_AmThuc_Comment_Rating", Storage="_ThongTinAmThuc", ThisKey="AmThuc_ID", OtherKey="AmThuc_ID", IsForeignKey=true)]
	public ThongTinAmThuc ThongTinAmThuc
	{
		get
		{
			return this._ThongTinAmThuc.Entity;
		}
		set
		{
			ThongTinAmThuc previousValue = this._ThongTinAmThuc.Entity;
			if (((previousValue != value) 
						|| (this._ThongTinAmThuc.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ThongTinAmThuc.Entity = null;
					previousValue.AmThuc_Comment_Ratings.Remove(this);
				}
				this._ThongTinAmThuc.Entity = value;
				if ((value != null))
				{
					value.AmThuc_Comment_Ratings.Add(this);
					this._AmThuc_ID = value.AmThuc_ID;
				}
				else
				{
					this._AmThuc_ID = default(Nullable<int>);
				}
				this.SendPropertyChanged("ThongTinAmThuc");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Event")]
public partial class Event : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Event_ID;
	
	private string _Title;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private EntitySet<Event_Comment_Rating> _Event_Comment_Ratings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEvent_IDChanging(int value);
    partial void OnEvent_IDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    #endregion
	
	public Event()
	{
		this._Event_Comment_Ratings = new EntitySet<Event_Comment_Rating>(new Action<Event_Comment_Rating>(this.attach_Event_Comment_Ratings), new Action<Event_Comment_Rating>(this.detach_Event_Comment_Ratings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Event_ID
	{
		get
		{
			return this._Event_ID;
		}
		set
		{
			if ((this._Event_ID != value))
			{
				this.OnEvent_IDChanging(value);
				this.SendPropertyChanging();
				this._Event_ID = value;
				this.SendPropertyChanged("Event_ID");
				this.OnEvent_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Event_Event_Comment_Rating", Storage="_Event_Comment_Ratings", ThisKey="Event_ID", OtherKey="Event_ID")]
	public EntitySet<Event_Comment_Rating> Event_Comment_Ratings
	{
		get
		{
			return this._Event_Comment_Ratings;
		}
		set
		{
			this._Event_Comment_Ratings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Event_Comment_Ratings(Event_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Event = this;
	}
	
	private void detach_Event_Comment_Ratings(Event_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.Event = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Travel_Comment_Rating")]
public partial class Travel_Comment_Rating : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Comment_ID;
	
	private System.Nullable<System.Guid> _User_ID;
	
	private System.Nullable<int> _Travel_ID;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private EntityRef<Account> _Account;
	
	private EntityRef<ThongTinDuLich> _ThongTinDuLich;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComment_IDChanging(int value);
    partial void OnComment_IDChanged();
    partial void OnUser_IDChanging(System.Nullable<System.Guid> value);
    partial void OnUser_IDChanged();
    partial void OnTravel_IDChanging(System.Nullable<int> value);
    partial void OnTravel_IDChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    #endregion
	
	public Travel_Comment_Rating()
	{
		this._Account = default(EntityRef<Account>);
		this._ThongTinDuLich = default(EntityRef<ThongTinDuLich>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Comment_ID
	{
		get
		{
			return this._Comment_ID;
		}
		set
		{
			if ((this._Comment_ID != value))
			{
				this.OnComment_IDChanging(value);
				this.SendPropertyChanging();
				this._Comment_ID = value;
				this.SendPropertyChanged("Comment_ID");
				this.OnComment_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				if (this._Account.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUser_IDChanging(value);
				this.SendPropertyChanging();
				this._User_ID = value;
				this.SendPropertyChanged("User_ID");
				this.OnUser_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Travel_ID", DbType="Int")]
	public System.Nullable<int> Travel_ID
	{
		get
		{
			return this._Travel_ID;
		}
		set
		{
			if ((this._Travel_ID != value))
			{
				if (this._ThongTinDuLich.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTravel_IDChanging(value);
				this.SendPropertyChanging();
				this._Travel_ID = value;
				this.SendPropertyChanged("Travel_ID");
				this.OnTravel_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(250)")]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Travel_Comment_Rating", Storage="_Account", ThisKey="User_ID", OtherKey="User_ID", IsForeignKey=true)]
	public Account Account
	{
		get
		{
			return this._Account.Entity;
		}
		set
		{
			Account previousValue = this._Account.Entity;
			if (((previousValue != value) 
						|| (this._Account.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Account.Entity = null;
					previousValue.Travel_Comment_Ratings.Remove(this);
				}
				this._Account.Entity = value;
				if ((value != null))
				{
					value.Travel_Comment_Ratings.Add(this);
					this._User_ID = value.User_ID;
				}
				else
				{
					this._User_ID = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("Account");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinDuLich_Travel_Comment_Rating", Storage="_ThongTinDuLich", ThisKey="Travel_ID", OtherKey="Travel_ID", IsForeignKey=true)]
	public ThongTinDuLich ThongTinDuLich
	{
		get
		{
			return this._ThongTinDuLich.Entity;
		}
		set
		{
			ThongTinDuLich previousValue = this._ThongTinDuLich.Entity;
			if (((previousValue != value) 
						|| (this._ThongTinDuLich.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ThongTinDuLich.Entity = null;
					previousValue.Travel_Comment_Ratings.Remove(this);
				}
				this._ThongTinDuLich.Entity = value;
				if ((value != null))
				{
					value.Travel_Comment_Ratings.Add(this);
					this._Travel_ID = value.Travel_ID;
				}
				else
				{
					this._Travel_ID = default(Nullable<int>);
				}
				this.SendPropertyChanged("ThongTinDuLich");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Event_Comment_Rating")]
public partial class Event_Comment_Rating : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Comment_ID;
	
	private System.Nullable<System.Guid> _User_ID;
	
	private System.Nullable<int> _Event_ID;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private EntityRef<Event> _Event;
	
	private EntityRef<Account> _Account;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComment_IDChanging(int value);
    partial void OnComment_IDChanged();
    partial void OnUser_IDChanging(System.Nullable<System.Guid> value);
    partial void OnUser_IDChanged();
    partial void OnEvent_IDChanging(System.Nullable<int> value);
    partial void OnEvent_IDChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    #endregion
	
	public Event_Comment_Rating()
	{
		this._Event = default(EntityRef<Event>);
		this._Account = default(EntityRef<Account>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Comment_ID
	{
		get
		{
			return this._Comment_ID;
		}
		set
		{
			if ((this._Comment_ID != value))
			{
				this.OnComment_IDChanging(value);
				this.SendPropertyChanging();
				this._Comment_ID = value;
				this.SendPropertyChanged("Comment_ID");
				this.OnComment_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				if (this._Account.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUser_IDChanging(value);
				this.SendPropertyChanging();
				this._User_ID = value;
				this.SendPropertyChanged("User_ID");
				this.OnUser_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event_ID", DbType="Int")]
	public System.Nullable<int> Event_ID
	{
		get
		{
			return this._Event_ID;
		}
		set
		{
			if ((this._Event_ID != value))
			{
				if (this._Event.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnEvent_IDChanging(value);
				this.SendPropertyChanging();
				this._Event_ID = value;
				this.SendPropertyChanged("Event_ID");
				this.OnEvent_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(250)")]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Event_Event_Comment_Rating", Storage="_Event", ThisKey="Event_ID", OtherKey="Event_ID", IsForeignKey=true)]
	public Event Event
	{
		get
		{
			return this._Event.Entity;
		}
		set
		{
			Event previousValue = this._Event.Entity;
			if (((previousValue != value) 
						|| (this._Event.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Event.Entity = null;
					previousValue.Event_Comment_Ratings.Remove(this);
				}
				this._Event.Entity = value;
				if ((value != null))
				{
					value.Event_Comment_Ratings.Add(this);
					this._Event_ID = value.Event_ID;
				}
				else
				{
					this._Event_ID = default(Nullable<int>);
				}
				this.SendPropertyChanged("Event");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Event_Comment_Rating", Storage="_Account", ThisKey="User_ID", OtherKey="User_ID", IsForeignKey=true)]
	public Account Account
	{
		get
		{
			return this._Account.Entity;
		}
		set
		{
			Account previousValue = this._Account.Entity;
			if (((previousValue != value) 
						|| (this._Account.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Account.Entity = null;
					previousValue.Event_Comment_Ratings.Remove(this);
				}
				this._Account.Entity = value;
				if ((value != null))
				{
					value.Event_Comment_Ratings.Add(this);
					this._User_ID = value.User_ID;
				}
				else
				{
					this._User_ID = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("Account");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hotel_Comment_Rating")]
public partial class Hotel_Comment_Rating : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Comment_ID;
	
	private System.Nullable<System.Guid> _User_ID;
	
	private System.Nullable<int> _Hotel_ID;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private EntityRef<Account> _Account;
	
	private EntityRef<ThongTinKhachSan> _ThongTinKhachSan;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComment_IDChanging(int value);
    partial void OnComment_IDChanged();
    partial void OnUser_IDChanging(System.Nullable<System.Guid> value);
    partial void OnUser_IDChanged();
    partial void OnHotel_IDChanging(System.Nullable<int> value);
    partial void OnHotel_IDChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    #endregion
	
	public Hotel_Comment_Rating()
	{
		this._Account = default(EntityRef<Account>);
		this._ThongTinKhachSan = default(EntityRef<ThongTinKhachSan>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Comment_ID
	{
		get
		{
			return this._Comment_ID;
		}
		set
		{
			if ((this._Comment_ID != value))
			{
				this.OnComment_IDChanging(value);
				this.SendPropertyChanging();
				this._Comment_ID = value;
				this.SendPropertyChanged("Comment_ID");
				this.OnComment_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				if (this._Account.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUser_IDChanging(value);
				this.SendPropertyChanging();
				this._User_ID = value;
				this.SendPropertyChanged("User_ID");
				this.OnUser_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel_ID", DbType="Int")]
	public System.Nullable<int> Hotel_ID
	{
		get
		{
			return this._Hotel_ID;
		}
		set
		{
			if ((this._Hotel_ID != value))
			{
				if (this._ThongTinKhachSan.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnHotel_IDChanging(value);
				this.SendPropertyChanging();
				this._Hotel_ID = value;
				this.SendPropertyChanged("Hotel_ID");
				this.OnHotel_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(250)")]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Hotel_Comment_Rating", Storage="_Account", ThisKey="User_ID", OtherKey="User_ID", IsForeignKey=true)]
	public Account Account
	{
		get
		{
			return this._Account.Entity;
		}
		set
		{
			Account previousValue = this._Account.Entity;
			if (((previousValue != value) 
						|| (this._Account.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Account.Entity = null;
					previousValue.Hotel_Comment_Ratings.Remove(this);
				}
				this._Account.Entity = value;
				if ((value != null))
				{
					value.Hotel_Comment_Ratings.Add(this);
					this._User_ID = value.User_ID;
				}
				else
				{
					this._User_ID = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("Account");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinKhachSan_Hotel_Comment_Rating", Storage="_ThongTinKhachSan", ThisKey="Hotel_ID", OtherKey="Hotel_ID", IsForeignKey=true)]
	public ThongTinKhachSan ThongTinKhachSan
	{
		get
		{
			return this._ThongTinKhachSan.Entity;
		}
		set
		{
			ThongTinKhachSan previousValue = this._ThongTinKhachSan.Entity;
			if (((previousValue != value) 
						|| (this._ThongTinKhachSan.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ThongTinKhachSan.Entity = null;
					previousValue.Hotel_Comment_Ratings.Remove(this);
				}
				this._ThongTinKhachSan.Entity = value;
				if ((value != null))
				{
					value.Hotel_Comment_Ratings.Add(this);
					this._Hotel_ID = value.Hotel_ID;
				}
				else
				{
					this._Hotel_ID = default(Nullable<int>);
				}
				this.SendPropertyChanged("ThongTinKhachSan");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rest_Comment_Rating")]
public partial class Rest_Comment_Rating : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Comment_ID;
	
	private System.Nullable<System.Guid> _User_ID;
	
	private System.Nullable<int> _Rest_ID;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private EntityRef<Account> _Account;
	
	private EntityRef<ThongTinNhaHang> _ThongTinNhaHang;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComment_IDChanging(int value);
    partial void OnComment_IDChanged();
    partial void OnUser_IDChanging(System.Nullable<System.Guid> value);
    partial void OnUser_IDChanged();
    partial void OnRest_IDChanging(System.Nullable<int> value);
    partial void OnRest_IDChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    #endregion
	
	public Rest_Comment_Rating()
	{
		this._Account = default(EntityRef<Account>);
		this._ThongTinNhaHang = default(EntityRef<ThongTinNhaHang>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Comment_ID
	{
		get
		{
			return this._Comment_ID;
		}
		set
		{
			if ((this._Comment_ID != value))
			{
				this.OnComment_IDChanging(value);
				this.SendPropertyChanging();
				this._Comment_ID = value;
				this.SendPropertyChanged("Comment_ID");
				this.OnComment_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				if (this._Account.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUser_IDChanging(value);
				this.SendPropertyChanging();
				this._User_ID = value;
				this.SendPropertyChanged("User_ID");
				this.OnUser_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rest_ID", DbType="Int")]
	public System.Nullable<int> Rest_ID
	{
		get
		{
			return this._Rest_ID;
		}
		set
		{
			if ((this._Rest_ID != value))
			{
				if (this._ThongTinNhaHang.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnRest_IDChanging(value);
				this.SendPropertyChanging();
				this._Rest_ID = value;
				this.SendPropertyChanged("Rest_ID");
				this.OnRest_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(250)")]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Rest_Comment_Rating", Storage="_Account", ThisKey="User_ID", OtherKey="User_ID", IsForeignKey=true)]
	public Account Account
	{
		get
		{
			return this._Account.Entity;
		}
		set
		{
			Account previousValue = this._Account.Entity;
			if (((previousValue != value) 
						|| (this._Account.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Account.Entity = null;
					previousValue.Rest_Comment_Ratings.Remove(this);
				}
				this._Account.Entity = value;
				if ((value != null))
				{
					value.Rest_Comment_Ratings.Add(this);
					this._User_ID = value.User_ID;
				}
				else
				{
					this._User_ID = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("Account");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinNhaHang_Rest_Comment_Rating", Storage="_ThongTinNhaHang", ThisKey="Rest_ID", OtherKey="Rest_ID", IsForeignKey=true)]
	public ThongTinNhaHang ThongTinNhaHang
	{
		get
		{
			return this._ThongTinNhaHang.Entity;
		}
		set
		{
			ThongTinNhaHang previousValue = this._ThongTinNhaHang.Entity;
			if (((previousValue != value) 
						|| (this._ThongTinNhaHang.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ThongTinNhaHang.Entity = null;
					previousValue.Rest_Comment_Ratings.Remove(this);
				}
				this._ThongTinNhaHang.Entity = value;
				if ((value != null))
				{
					value.Rest_Comment_Ratings.Add(this);
					this._Rest_ID = value.Rest_ID;
				}
				else
				{
					this._Rest_ID = default(Nullable<int>);
				}
				this.SendPropertyChanged("ThongTinNhaHang");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinAmThuc")]
public partial class ThongTinAmThuc : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AmThuc_ID;
	
	private string _Title;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private EntitySet<AmThuc_Comment_Rating> _AmThuc_Comment_Ratings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAmThuc_IDChanging(int value);
    partial void OnAmThuc_IDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    #endregion
	
	public ThongTinAmThuc()
	{
		this._AmThuc_Comment_Ratings = new EntitySet<AmThuc_Comment_Rating>(new Action<AmThuc_Comment_Rating>(this.attach_AmThuc_Comment_Ratings), new Action<AmThuc_Comment_Rating>(this.detach_AmThuc_Comment_Ratings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmThuc_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int AmThuc_ID
	{
		get
		{
			return this._AmThuc_ID;
		}
		set
		{
			if ((this._AmThuc_ID != value))
			{
				this.OnAmThuc_IDChanging(value);
				this.SendPropertyChanging();
				this._AmThuc_ID = value;
				this.SendPropertyChanged("AmThuc_ID");
				this.OnAmThuc_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinAmThuc_AmThuc_Comment_Rating", Storage="_AmThuc_Comment_Ratings", ThisKey="AmThuc_ID", OtherKey="AmThuc_ID")]
	public EntitySet<AmThuc_Comment_Rating> AmThuc_Comment_Ratings
	{
		get
		{
			return this._AmThuc_Comment_Ratings;
		}
		set
		{
			this._AmThuc_Comment_Ratings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_AmThuc_Comment_Ratings(AmThuc_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinAmThuc = this;
	}
	
	private void detach_AmThuc_Comment_Ratings(AmThuc_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinAmThuc = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinNhaHang")]
public partial class ThongTinNhaHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Rest_ID;
	
	private string _Name;
	
	private string _Address;
	
	private string _Phone;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private EntitySet<Rest_Comment_Rating> _Rest_Comment_Ratings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRest_IDChanging(int value);
    partial void OnRest_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    #endregion
	
	public ThongTinNhaHang()
	{
		this._Rest_Comment_Ratings = new EntitySet<Rest_Comment_Rating>(new Action<Rest_Comment_Rating>(this.attach_Rest_Comment_Ratings), new Action<Rest_Comment_Rating>(this.detach_Rest_Comment_Ratings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rest_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Rest_ID
	{
		get
		{
			return this._Rest_ID;
		}
		set
		{
			if ((this._Rest_ID != value))
			{
				this.OnRest_IDChanging(value);
				this.SendPropertyChanging();
				this._Rest_ID = value;
				this.SendPropertyChanged("Rest_ID");
				this.OnRest_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinNhaHang_Rest_Comment_Rating", Storage="_Rest_Comment_Ratings", ThisKey="Rest_ID", OtherKey="Rest_ID")]
	public EntitySet<Rest_Comment_Rating> Rest_Comment_Ratings
	{
		get
		{
			return this._Rest_Comment_Ratings;
		}
		set
		{
			this._Rest_Comment_Ratings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Rest_Comment_Ratings(Rest_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinNhaHang = this;
	}
	
	private void detach_Rest_Comment_Ratings(Rest_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinNhaHang = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinDuLich")]
public partial class ThongTinDuLich : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Travel_ID;
	
	private string _Name;
	
	private string _Address;
	
	private string _Phone;
	
	private string _ShortDescription;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private string _InsertDay;
	
	private string _InsertMonth;
	
	private System.Nullable<int> _CommentNum;
	
	private string _CoverPic;
	
	private string _Pic1;
	
	private string _Pic2;
	
	private string _Pic3;
	
	private string _Pic4;
	
	private string _Pic5;
	
	private string _Pic6;
	
	private System.Nullable<int> _LikeNum;
	
	private EntitySet<Travel_Comment_Rating> _Travel_Comment_Ratings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTravel_IDChanging(int value);
    partial void OnTravel_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnShortDescriptionChanging(string value);
    partial void OnShortDescriptionChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    partial void OnInsertDayChanging(string value);
    partial void OnInsertDayChanged();
    partial void OnInsertMonthChanging(string value);
    partial void OnInsertMonthChanged();
    partial void OnCommentNumChanging(System.Nullable<int> value);
    partial void OnCommentNumChanged();
    partial void OnCoverPicChanging(string value);
    partial void OnCoverPicChanged();
    partial void OnPic1Changing(string value);
    partial void OnPic1Changed();
    partial void OnPic2Changing(string value);
    partial void OnPic2Changed();
    partial void OnPic3Changing(string value);
    partial void OnPic3Changed();
    partial void OnPic4Changing(string value);
    partial void OnPic4Changed();
    partial void OnPic5Changing(string value);
    partial void OnPic5Changed();
    partial void OnPic6Changing(string value);
    partial void OnPic6Changed();
    partial void OnLikeNumChanging(System.Nullable<int> value);
    partial void OnLikeNumChanged();
    #endregion
	
	public ThongTinDuLich()
	{
		this._Travel_Comment_Ratings = new EntitySet<Travel_Comment_Rating>(new Action<Travel_Comment_Rating>(this.attach_Travel_Comment_Ratings), new Action<Travel_Comment_Rating>(this.detach_Travel_Comment_Ratings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Travel_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Travel_ID
	{
		get
		{
			return this._Travel_ID;
		}
		set
		{
			if ((this._Travel_ID != value))
			{
				this.OnTravel_IDChanging(value);
				this.SendPropertyChanging();
				this._Travel_ID = value;
				this.SendPropertyChanged("Travel_ID");
				this.OnTravel_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDescription", DbType="NVarChar(1000)")]
	public string ShortDescription
	{
		get
		{
			return this._ShortDescription;
		}
		set
		{
			if ((this._ShortDescription != value))
			{
				this.OnShortDescriptionChanging(value);
				this.SendPropertyChanging();
				this._ShortDescription = value;
				this.SendPropertyChanged("ShortDescription");
				this.OnShortDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDay", DbType="Char(2)")]
	public string InsertDay
	{
		get
		{
			return this._InsertDay;
		}
		set
		{
			if ((this._InsertDay != value))
			{
				this.OnInsertDayChanging(value);
				this.SendPropertyChanging();
				this._InsertDay = value;
				this.SendPropertyChanged("InsertDay");
				this.OnInsertDayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertMonth", DbType="Char(3)")]
	public string InsertMonth
	{
		get
		{
			return this._InsertMonth;
		}
		set
		{
			if ((this._InsertMonth != value))
			{
				this.OnInsertMonthChanging(value);
				this.SendPropertyChanging();
				this._InsertMonth = value;
				this.SendPropertyChanged("InsertMonth");
				this.OnInsertMonthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentNum", DbType="Int")]
	public System.Nullable<int> CommentNum
	{
		get
		{
			return this._CommentNum;
		}
		set
		{
			if ((this._CommentNum != value))
			{
				this.OnCommentNumChanging(value);
				this.SendPropertyChanging();
				this._CommentNum = value;
				this.SendPropertyChanged("CommentNum");
				this.OnCommentNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoverPic", DbType="NVarChar(255)")]
	public string CoverPic
	{
		get
		{
			return this._CoverPic;
		}
		set
		{
			if ((this._CoverPic != value))
			{
				this.OnCoverPicChanging(value);
				this.SendPropertyChanging();
				this._CoverPic = value;
				this.SendPropertyChanged("CoverPic");
				this.OnCoverPicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic1", DbType="NVarChar(255)")]
	public string Pic1
	{
		get
		{
			return this._Pic1;
		}
		set
		{
			if ((this._Pic1 != value))
			{
				this.OnPic1Changing(value);
				this.SendPropertyChanging();
				this._Pic1 = value;
				this.SendPropertyChanged("Pic1");
				this.OnPic1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic2", DbType="NVarChar(255)")]
	public string Pic2
	{
		get
		{
			return this._Pic2;
		}
		set
		{
			if ((this._Pic2 != value))
			{
				this.OnPic2Changing(value);
				this.SendPropertyChanging();
				this._Pic2 = value;
				this.SendPropertyChanged("Pic2");
				this.OnPic2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic3", DbType="NVarChar(255)")]
	public string Pic3
	{
		get
		{
			return this._Pic3;
		}
		set
		{
			if ((this._Pic3 != value))
			{
				this.OnPic3Changing(value);
				this.SendPropertyChanging();
				this._Pic3 = value;
				this.SendPropertyChanged("Pic3");
				this.OnPic3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic4", DbType="NVarChar(255)")]
	public string Pic4
	{
		get
		{
			return this._Pic4;
		}
		set
		{
			if ((this._Pic4 != value))
			{
				this.OnPic4Changing(value);
				this.SendPropertyChanging();
				this._Pic4 = value;
				this.SendPropertyChanged("Pic4");
				this.OnPic4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic5", DbType="NVarChar(255)")]
	public string Pic5
	{
		get
		{
			return this._Pic5;
		}
		set
		{
			if ((this._Pic5 != value))
			{
				this.OnPic5Changing(value);
				this.SendPropertyChanging();
				this._Pic5 = value;
				this.SendPropertyChanged("Pic5");
				this.OnPic5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic6", DbType="NVarChar(255)")]
	public string Pic6
	{
		get
		{
			return this._Pic6;
		}
		set
		{
			if ((this._Pic6 != value))
			{
				this.OnPic6Changing(value);
				this.SendPropertyChanging();
				this._Pic6 = value;
				this.SendPropertyChanged("Pic6");
				this.OnPic6Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LikeNum", DbType="Int")]
	public System.Nullable<int> LikeNum
	{
		get
		{
			return this._LikeNum;
		}
		set
		{
			if ((this._LikeNum != value))
			{
				this.OnLikeNumChanging(value);
				this.SendPropertyChanging();
				this._LikeNum = value;
				this.SendPropertyChanged("LikeNum");
				this.OnLikeNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinDuLich_Travel_Comment_Rating", Storage="_Travel_Comment_Ratings", ThisKey="Travel_ID", OtherKey="Travel_ID")]
	public EntitySet<Travel_Comment_Rating> Travel_Comment_Ratings
	{
		get
		{
			return this._Travel_Comment_Ratings;
		}
		set
		{
			this._Travel_Comment_Ratings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Travel_Comment_Ratings(Travel_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinDuLich = this;
	}
	
	private void detach_Travel_Comment_Ratings(Travel_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinDuLich = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinKhachSan")]
public partial class ThongTinKhachSan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Hotel_ID;
	
	private string _Name;
	
	private string _Address;
	
	private string _Phone;
	
	private string _ShortDescription;
	
	private string _Content;
	
	private System.Nullable<int> _Rating;
	
	private string _InsertDay;
	
	private string _InsertMonth;
	
	private System.Nullable<int> _CommentNum;
	
	private string _CoverPic;
	
	private string _Pic1;
	
	private string _Pic2;
	
	private string _Pic3;
	
	private string _Pic4;
	
	private string _Pic5;
	
	private string _Pic6;
	
	private System.Nullable<int> _LikeNum;
	
	private EntitySet<Hotel_Comment_Rating> _Hotel_Comment_Ratings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHotel_IDChanging(int value);
    partial void OnHotel_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnShortDescriptionChanging(string value);
    partial void OnShortDescriptionChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    partial void OnInsertDayChanging(string value);
    partial void OnInsertDayChanged();
    partial void OnInsertMonthChanging(string value);
    partial void OnInsertMonthChanged();
    partial void OnCommentNumChanging(System.Nullable<int> value);
    partial void OnCommentNumChanged();
    partial void OnCoverPicChanging(string value);
    partial void OnCoverPicChanged();
    partial void OnPic1Changing(string value);
    partial void OnPic1Changed();
    partial void OnPic2Changing(string value);
    partial void OnPic2Changed();
    partial void OnPic3Changing(string value);
    partial void OnPic3Changed();
    partial void OnPic4Changing(string value);
    partial void OnPic4Changed();
    partial void OnPic5Changing(string value);
    partial void OnPic5Changed();
    partial void OnPic6Changing(string value);
    partial void OnPic6Changed();
    partial void OnLikeNumChanging(System.Nullable<int> value);
    partial void OnLikeNumChanged();
    #endregion
	
	public ThongTinKhachSan()
	{
		this._Hotel_Comment_Ratings = new EntitySet<Hotel_Comment_Rating>(new Action<Hotel_Comment_Rating>(this.attach_Hotel_Comment_Ratings), new Action<Hotel_Comment_Rating>(this.detach_Hotel_Comment_Ratings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Hotel_ID
	{
		get
		{
			return this._Hotel_ID;
		}
		set
		{
			if ((this._Hotel_ID != value))
			{
				this.OnHotel_IDChanging(value);
				this.SendPropertyChanging();
				this._Hotel_ID = value;
				this.SendPropertyChanged("Hotel_ID");
				this.OnHotel_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDescription", DbType="NVarChar(1000)")]
	public string ShortDescription
	{
		get
		{
			return this._ShortDescription;
		}
		set
		{
			if ((this._ShortDescription != value))
			{
				this.OnShortDescriptionChanging(value);
				this.SendPropertyChanging();
				this._ShortDescription = value;
				this.SendPropertyChanged("ShortDescription");
				this.OnShortDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
	public System.Nullable<int> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDay", DbType="Char(2)")]
	public string InsertDay
	{
		get
		{
			return this._InsertDay;
		}
		set
		{
			if ((this._InsertDay != value))
			{
				this.OnInsertDayChanging(value);
				this.SendPropertyChanging();
				this._InsertDay = value;
				this.SendPropertyChanged("InsertDay");
				this.OnInsertDayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertMonth", DbType="Char(3)")]
	public string InsertMonth
	{
		get
		{
			return this._InsertMonth;
		}
		set
		{
			if ((this._InsertMonth != value))
			{
				this.OnInsertMonthChanging(value);
				this.SendPropertyChanging();
				this._InsertMonth = value;
				this.SendPropertyChanged("InsertMonth");
				this.OnInsertMonthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentNum", DbType="Int")]
	public System.Nullable<int> CommentNum
	{
		get
		{
			return this._CommentNum;
		}
		set
		{
			if ((this._CommentNum != value))
			{
				this.OnCommentNumChanging(value);
				this.SendPropertyChanging();
				this._CommentNum = value;
				this.SendPropertyChanged("CommentNum");
				this.OnCommentNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoverPic", DbType="NVarChar(255)")]
	public string CoverPic
	{
		get
		{
			return this._CoverPic;
		}
		set
		{
			if ((this._CoverPic != value))
			{
				this.OnCoverPicChanging(value);
				this.SendPropertyChanging();
				this._CoverPic = value;
				this.SendPropertyChanged("CoverPic");
				this.OnCoverPicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic1", DbType="NVarChar(255)")]
	public string Pic1
	{
		get
		{
			return this._Pic1;
		}
		set
		{
			if ((this._Pic1 != value))
			{
				this.OnPic1Changing(value);
				this.SendPropertyChanging();
				this._Pic1 = value;
				this.SendPropertyChanged("Pic1");
				this.OnPic1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic2", DbType="NVarChar(255)")]
	public string Pic2
	{
		get
		{
			return this._Pic2;
		}
		set
		{
			if ((this._Pic2 != value))
			{
				this.OnPic2Changing(value);
				this.SendPropertyChanging();
				this._Pic2 = value;
				this.SendPropertyChanged("Pic2");
				this.OnPic2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic3", DbType="NVarChar(255)")]
	public string Pic3
	{
		get
		{
			return this._Pic3;
		}
		set
		{
			if ((this._Pic3 != value))
			{
				this.OnPic3Changing(value);
				this.SendPropertyChanging();
				this._Pic3 = value;
				this.SendPropertyChanged("Pic3");
				this.OnPic3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic4", DbType="NVarChar(255)")]
	public string Pic4
	{
		get
		{
			return this._Pic4;
		}
		set
		{
			if ((this._Pic4 != value))
			{
				this.OnPic4Changing(value);
				this.SendPropertyChanging();
				this._Pic4 = value;
				this.SendPropertyChanged("Pic4");
				this.OnPic4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic5", DbType="NVarChar(255)")]
	public string Pic5
	{
		get
		{
			return this._Pic5;
		}
		set
		{
			if ((this._Pic5 != value))
			{
				this.OnPic5Changing(value);
				this.SendPropertyChanging();
				this._Pic5 = value;
				this.SendPropertyChanged("Pic5");
				this.OnPic5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic6", DbType="NVarChar(255)")]
	public string Pic6
	{
		get
		{
			return this._Pic6;
		}
		set
		{
			if ((this._Pic6 != value))
			{
				this.OnPic6Changing(value);
				this.SendPropertyChanging();
				this._Pic6 = value;
				this.SendPropertyChanged("Pic6");
				this.OnPic6Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LikeNum", DbType="Int")]
	public System.Nullable<int> LikeNum
	{
		get
		{
			return this._LikeNum;
		}
		set
		{
			if ((this._LikeNum != value))
			{
				this.OnLikeNumChanging(value);
				this.SendPropertyChanging();
				this._LikeNum = value;
				this.SendPropertyChanged("LikeNum");
				this.OnLikeNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinKhachSan_Hotel_Comment_Rating", Storage="_Hotel_Comment_Ratings", ThisKey="Hotel_ID", OtherKey="Hotel_ID")]
	public EntitySet<Hotel_Comment_Rating> Hotel_Comment_Ratings
	{
		get
		{
			return this._Hotel_Comment_Ratings;
		}
		set
		{
			this._Hotel_Comment_Ratings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Hotel_Comment_Ratings(Hotel_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinKhachSan = this;
	}
	
	private void detach_Hotel_Comment_Ratings(Hotel_Comment_Rating entity)
	{
		this.SendPropertyChanging();
		entity.ThongTinKhachSan = null;
	}
}
#pragma warning restore 1591
